@startuml
set separator none
title Inventory Module - Containers

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

AddElementTag("Context", $bgColor="#69beff", $borderColor="#4985b2", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Container", $bgColor="#95d1fe", $borderColor="#6892b1", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("External", $bgColor="#d0a7ff", $borderColor="#9174b2", $fontColor="#000000", $sprite="", $shadowing="")

AddRelTag("Relationship", $textColor="#000000", $lineColor="#000000", $lineStyle = "")

AddBoundaryTag("Context", $bgColor="#ffffff", $borderColor="#4985b2", $fontColor="#4985b2", $shadowing="")

System(ConfigurationsModule, "Configurations Module", $descr="", $tags="Context", $link="")
System_Ext(ECommerce, "E-Commerce", $descr="", $tags="External", $link="")
System(DatabaseModule, "Database Module", $descr="", $tags="Context", $link="")
System(MissionsModule, "Missions Module", $descr="", $tags="Context", $link="")

System_Boundary("InventoryModule_boundary", "Inventory Module", $tags="Context") {
  Container(InventoryModule.CycleCounting, "Cycle Counting", $techn="", $descr="Scheduled", $tags="Container", $link="")
  Container(InventoryModule.UnitSupplier, "Unit Supplier", $techn="", $descr="Microservice", $tags="Container", $link="")
  Container(InventoryModule.MissionGenerator, "Mission Generator", $techn="", $descr="Microservice", $tags="Container", $link="")
  Container(InventoryModule.SchemaValidation, "Schema Validation", $techn="", $descr="Microservice", $tags="Container", $link="")
  Container(InventoryModule.Authentication, "Authentication", $techn="", $descr="Firewall", $tags="Container", $link="")
}

Rel_D(ConfigurationsModule, DatabaseModule, "Change the configuration", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, InventoryModule.CycleCounting, "Update schedule", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, InventoryModule.UnitSupplier, "Update supply rules", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(MissionsModule, DatabaseModule, "Updates the status", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(InventoryModule.CycleCounting, MissionsModule, "Create counting missions", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(InventoryModule.UnitSupplier, MissionsModule, "Create supplying missions", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(DatabaseModule, InventoryModule.MissionGenerator, "Retrieve Layout and Units", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(InventoryModule.MissionGenerator, MissionsModule, "Create a picking mission", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(InventoryModule.MissionGenerator, InventoryModule.UnitSupplier, "Send the leftovers", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(InventoryModule.SchemaValidation, DatabaseModule, "Sends the order", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(InventoryModule.SchemaValidation, InventoryModule.MissionGenerator, "Request units", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ECommerce, InventoryModule.Authentication, "Sends the order", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(InventoryModule.Authentication, InventoryModule.SchemaValidation, "Redirects", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml