@startuml
set separator none
title Analytics Module - Containers

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

AddElementTag("Employee", $bgColor="#f9d055", $borderColor="#ae913b", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Context", $bgColor="#69beff", $borderColor="#4985b2", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Container,Desktop", $bgColor="#8af0ac", $borderColor="#60a878", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Container,Database", $bgColor="#95d1fe", $borderColor="#6892b1", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Container", $bgColor="#95d1fe", $borderColor="#6892b1", $fontColor="#000000", $sprite="", $shadowing="")

AddRelTag("Relationship", $textColor="#000000", $lineColor="#000000", $lineStyle = "")

AddBoundaryTag("Context", $bgColor="#ffffff", $borderColor="#4985b2", $fontColor="#4985b2", $shadowing="")

System(ConfigurationsModule, "Configurations Module", $descr="", $tags="Context", $link="")
Person(LogisticAnalyst, "Logistic Analyst", $descr="", $tags="Employee", $link="")
System(DatabaseModule, "Database Module", $descr="", $tags="Context", $link="")
System(MissionsModule, "Missions Module", $descr="", $tags="Context", $link="")

System_Boundary("AnalyticsModule_boundary", "Analytics Module", $tags="Context") {
  Container(AnalyticsModule.AnalyticsView, "Analytics View", $techn="", $descr="Responsive App", $tags="Container,Desktop", $link="")
  Container(AnalyticsModule.AnalyticsWrapper, "Analytics Wrapper", $techn="", $descr="Microservice", $tags="Container", $link="")
  ContainerDb(AnalyticsModule.AnalyticsData, "Analytics Data", $techn="", $descr="SQL Database", $tags="Container,Database", $link="")
  Container(AnalyticsModule.StatisticsCalculator, "Statistics Calculator", $techn="", $descr="Scheduled", $tags="Container", $link="")
  Container(AnalyticsModule.SchemaValidation, "Schema Validation", $techn="", $descr="Microservice", $tags="Container", $link="")
  Container(AnalyticsModule.Authentication, "Authentication", $techn="", $descr="Firewall", $tags="Container", $link="")
}

Rel_D(ConfigurationsModule, DatabaseModule, "Change the configuration", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, AnalyticsModule.StatisticsCalculator, "Update schedule", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(MissionsModule, DatabaseModule, "Updates the status", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(LogisticAnalyst, AnalyticsModule.AnalyticsView, "Watches the performance", $techn="", $tags="Relationship", $link="")
Rel_D(AnalyticsModule.AnalyticsWrapper, AnalyticsModule.AnalyticsData, "Manages the data", $techn="", $tags="Relationship", $link="")
Rel_D(DatabaseModule, AnalyticsModule.StatisticsCalculator, "Retrieves the data", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(MissionsModule, AnalyticsModule.StatisticsCalculator, "Retrieves the data", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(AnalyticsModule.StatisticsCalculator, AnalyticsModule.AnalyticsWrapper, "Sends the results", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(AnalyticsModule.SchemaValidation, AnalyticsModule.AnalyticsWrapper, "Retrieves the data", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(AnalyticsModule.AnalyticsView, AnalyticsModule.Authentication, "Request the data", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(AnalyticsModule.Authentication, AnalyticsModule.SchemaValidation, "Redirects", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml