@startuml
set separator none
title Reception Module - Containers

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

AddElementTag("Employee", $bgColor="#f9d055", $borderColor="#ae913b", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Context", $bgColor="#69beff", $borderColor="#4985b2", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Container,Desktop", $bgColor="#8af0ac", $borderColor="#60a878", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Container", $bgColor="#95d1fe", $borderColor="#6892b1", $fontColor="#000000", $sprite="", $shadowing="")

AddRelTag("Relationship", $textColor="#000000", $lineColor="#000000", $lineStyle = "")

AddBoundaryTag("Context", $bgColor="#ffffff", $borderColor="#4985b2", $fontColor="#4985b2", $shadowing="")

Person(ReceivingEmployee, "Receiving Employee", $descr="", $tags="Employee", $link="")
System(ConfigurationsModule, "Configurations Module", $descr="", $tags="Context", $link="")
System(DatabaseModule, "Database Module", $descr="", $tags="Context", $link="")

System_Boundary("ReceptionModule_boundary", "Reception Module", $tags="Context") {
  Container(ReceptionModule.ReceptionForm, "Reception Form", $techn="", $descr="Responsive App", $tags="Container,Desktop", $link="")
  Container(ReceptionModule.SchemaValidation, "Schema Validation", $techn="", $descr="Microservice", $tags="Container", $link="")
  Container(ReceptionModule.ReceptionSupplier, "Reception Supplier", $techn="", $descr="Scheduled", $tags="Container", $link="")
  Container(ReceptionModule.Authentication, "Authentication", $techn="", $descr="Firewall", $tags="Container", $link="")
}

Rel_D(ReceivingEmployee, ReceptionModule.ReceptionForm, "Fills a form", $techn="", $tags="Relationship", $link="")
Rel_D(ReceptionModule.SchemaValidation, DatabaseModule, "Sends new values", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ReceptionModule.ReceptionSupplier, DatabaseModule, "Create supplyment orders", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ReceptionModule.ReceptionForm, ReceptionModule.Authentication, "Sends the form", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(ReceptionModule.Authentication, ReceptionModule.SchemaValidation, "Redirects", $techn="", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, DatabaseModule, "Change the configuration", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, ReceptionModule.ReceptionSupplier, "Update schedule", $techn="Message Broker", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml