@startuml
set separator none
title Configurations Module - System Context

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

AddElementTag("Employee", $bgColor="#f9d055", $borderColor="#ae913b", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Context", $bgColor="#69beff", $borderColor="#4985b2", $fontColor="#000000", $sprite="", $shadowing="")

AddRelTag("Relationship", $textColor="#000000", $lineColor="#000000", $lineStyle = "")

AddBoundaryTag("Operation Managers", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "Operation Managers", $tags="Operation Managers") {
  Person(Administrator, "Administrator", $descr="", $tags="Employee", $link="")
}

System(ReceptionModule, "Reception Module", $descr="", $tags="Context", $link="")
System(AnalyticsModule, "Analytics Module", $descr="", $tags="Context", $link="")
System(ConfigurationsModule, "Configurations Module", $descr="", $tags="Context", $link="")
System(DatabaseModule, "Database Module", $descr="", $tags="Context", $link="")
System(InventoryModule, "Inventory Module", $descr="", $tags="Context", $link="")

Rel_D(ReceptionModule, DatabaseModule, "Sends new values", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(Administrator, ConfigurationsModule, "Make changes with", $techn="", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, DatabaseModule, "Change the configuration", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, AnalyticsModule, "Update schedule", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, InventoryModule, "Update schedule", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, ReceptionModule, "Update schedule", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(DatabaseModule, InventoryModule, "Retrieve Layout and Units", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(InventoryModule, DatabaseModule, "Sends the order", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(DatabaseModule, AnalyticsModule, "Retrieves the data", $techn="Message Broker", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml