@startuml
set separator none
title Layout Module - System Context

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

AddElementTag("Employee", $bgColor="#f9d055", $borderColor="#ae913b", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Context", $bgColor="#69beff", $borderColor="#4985b2", $fontColor="#000000", $sprite="", $shadowing="")

AddRelTag("Relationship", $textColor="#000000", $lineColor="#000000", $lineStyle = "")

AddBoundaryTag("Operation Managers", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "Operation Managers", $tags="Operation Managers") {
  Person(LayoutManager, "Layout Manager", $descr="", $tags="Employee", $link="")
}

System(LayoutModule, "Layout Module", $descr="", $tags="Context", $link="")
System(DatabaseModule, "Database Module", $descr="", $tags="Context", $link="")
System(MissionsModule, "Missions Module", $descr="", $tags="Context", $link="")

Rel_D(MissionsModule, DatabaseModule, "Updates the status", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(LayoutManager, LayoutModule, "Creates or modifies layout", $techn="", $tags="Relationship", $link="")
Rel_D(LayoutModule, DatabaseModule, "Sends new layout", $techn="HTTPS Request", $tags="Relationship", $link="")
Rel_D(LayoutModule, MissionsModule, "Sends updates required", $techn="Message Broker", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml