@startuml
set separator none
title Reception Module - System Context

left to right direction

!include <C4/C4>
!include <C4/C4_Context>

AddElementTag("Employee", $bgColor="#f9d055", $borderColor="#ae913b", $fontColor="#000000", $sprite="", $shadowing="")
AddElementTag("Context", $bgColor="#69beff", $borderColor="#4985b2", $fontColor="#000000", $sprite="", $shadowing="")

AddRelTag("Relationship", $textColor="#000000", $lineColor="#000000", $lineStyle = "")

Enterprise_Boundary(enterprise, "SLC-wms") {
  System(ReceptionModule, "Reception Module", $descr="", $tags="Context", $link="")
  System(ConfigurationsModule, "Configurations Module", $descr="", $tags="Context", $link="")
  System(DatabaseModule, "Database Module", $descr="", $tags="Context", $link="")
}

AddBoundaryTag("Operation Employees", $borderColor="#cccccc", $fontColor="#cccccc")
Boundary(group_1, "Operation Employees", $tags="Operation Employees") {
  Person_Ext(ReceivingEmployee, "Receiving Employee", $descr="", $tags="Employee", $link="")
}


Rel_D(ReceivingEmployee, ReceptionModule, "Fills a form", $techn="", $tags="Relationship", $link="")
Rel_D(ReceptionModule, DatabaseModule, "Sends new values", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, DatabaseModule, "Change the configuration", $techn="Message Broker", $tags="Relationship", $link="")
Rel_D(ConfigurationsModule, ReceptionModule, "Update schedule", $techn="Message Broker", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml