name: Deploy to Github Pages

on:
    push:
        branches: ["main"]

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages-deployment"
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        container:
            image: ghcr.io/avisi-cloud/structurizr-site-generatr
            options: --user root
        steps:
          - name: Git Checkout
            uses: actions/checkout@v4

          - name: Build Site with Generatr
            run: |
                /opt/structurizr-site-generatr/bin/structurizr-site-generatr generate-site \
                -w src/workspace.dsl \
                --assets-dir src/assets \
                --branches main \
                --default-branch main

          - name: Setup Github Pages
            if: ${{ success() }}
            uses: actions/configure-pages@v3

          - name: Upload Artifact
            if: ${{ success() }}
            uses: actions/upload-pages-artifact@v2
            with:
                path: 'build/site'

          - name: Deploy to GitHub Pages
            if: ${{ success() }}
            id: deployment
            uses: actions/deploy-pages@v2